# Generated by Django 5.2.10 on 2026-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Čaj', 'Tea'), ('Káva', 'Coffe'), ('Zákusky', 'Desserts')], max_length=100, verbose_name='Typ položky'),
        ),
    ]
