# Generated by Django 5.2.10 on 2026-01-20 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0003_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Souhrn objednávky'},
        ),
        migrations.AddField(
            model_name='order',
            name='declinedBy',
            field=models.ManyToManyField(blank=True, related_name='declined_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Čaj', 'Tea'), ('Káva', 'Coffe'), ('Zákusky', 'Desserts')], default='Čaj', max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='itemName',
            field=models.CharField(max_length=100, unique=True, verbose_name='Položka'),
        ),
    ]
