# Generated by Django 5.2.10 on 2026-01-20 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0004_alter_orderitem_options_order_declinedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='declinedBy',
            field=models.ManyToManyField(blank=True, null=True, related_name='declined_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
