# Generated by Django 5.2.10 on 2026-01-20 19:20

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0005_alter_order_declinedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='itemName',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='acceptedTime',
            new_name='accepted_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='assignedEmployee',
            new_name='assigned_employee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='completedTime',
            new_name='completed_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderID',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderStatus',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderTime',
            new_name='order_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tableID',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='tableName',
            new_name='table_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='declinedBy',
        ),
        migrations.AddField(
            model_name='order',
            name='declined_by',
            field=models.ManyToManyField(blank=True, related_name='declined_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
