# Generated by Django 5.2.10 on 2026-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0006_rename_itemname_menuitem_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Čaj', 'Tea'), ('Káva', 'Coffee'), ('Zákusky', 'Desserts')], default='Čaj', max_length=100),
        ),
    ]
