# Generated by Django 5.2.11 on 2026-02-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0007_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='late_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='late_completion',
            field=models.BooleanField(default=False),
        ),
    ]
